name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        where cmake || echo no cmake
        where ninja || echo no ninja
        where gcc || echo no gcc
        where python || echo no python
        where 7z || echo no 7z
        set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
        call vcvars64.bat
        where cmake || echo no cmake
        where ninja || echo no ninja
        where gcc || echo no gcc
        where python || echo no python
        where 7z || echo no 7z
        pyfind C:\hostedtoolcache\windows > hostedtoolcache.txt
        pyfind C:\ProgramData\Chocolatey > chocolatey.txt
        pyfind C:\Program Files\Microsoft Visual Studio > visual_studio.txt
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: hostedtoolcache
        path: |
          hostedtoolcache.txt
          chocolatey.txt
          visual_studio.txt
