name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        pushd C:\temp
            echo %CD%
            pushd %GITHUB_WORKSPACE%
                echo %CD%
            popd
        popd
