name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%USERPROFILE%\Miniconda3;%USERPROFILE%\Miniconda3\Scripts;%PATH%
        pip install mugicli
        pyfind C:\ -maxdepth 3 > windows-latest-listing.txt
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: windows-latest-listing
        path: windows-latest-listing.txt
