name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
        where cmake || echo no cmake
        where ninja || echo no ninja
        where gcc || echo no gcc
        where python || echo no python
        where 7z || echo no 7z
        call vcvars64.bat
        where cmake || echo no cmake
        where ninja || echo no ninja
        where gcc || echo no gcc
        where python || echo no python
        where 7z || echo no 7z
        pip install pyfindlib
        echo C:\hostedtoolcache\windows
        pyfind C:\hostedtoolcache\windows > hostedtoolcache.txt
        echo C:\ProgramData\Chocolatey
        pyfind C:\ProgramData\Chocolatey > chocolatey.txt
        echo C:\Program Files\Microsoft Visual Studio
        pyfind "C:\Program Files\Microsoft Visual Studio" > visual_studio.txt
        echo C:\Program Files
        pyfind "C:\Program Files" > program_files.txt
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: hostedtoolcache
        path: |
          hostedtoolcache.txt
          chocolatey.txt
          visual_studio.txt
          program_files.txt
