name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: cache date.txt
      uses: actions/cache@v4
      with:
        path: date.txt
        key: foo
    - name: main
      shell: cmd
      run: |
        if not exist date.txt date /t > date.txt
        type date.txt
