name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: cache foo
      uses: actions/cache@v3
      with:
        path: C:\foo
        key: foo
    - name: cache bar
      uses: actions/cache@v3
      with:
        path: C:\bar
        key: bar
    - name: main
      shell: cmd
      run: |
        if not exist "C:\foo" mkdir "C:\foo"
        if not exist "C:\bar" mkdir "C:\bar"
        echo 1 > C:\foo\1.txt
        echo 2 > C:\bar\1.txt
