name: main-1
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        pip install mugicli
        pyfor -n 10 --blank-line -- cmd /c "pyecho -n 1 > :iter:.txt && pysleep 10 && pycat *.txt"
