name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: a
      shell: cmd
      run: |
        echo 1 %GITHUB_ACTION_PATH%
        echo 2 ${{ github.action_path }}
    - name: b
      shell: cmd
      run: |
        echo 3
        if exist C:\Temp goto b_end
        echo 4
        :b_end
    - name: c
      shell: cmd
      run: set
    - name: main
      shell: cmd
      run: echo 5
