name: main2
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        pip install mugicli
        pysleep 1
        echo 2 > 1.txt
        pysleep 1
        type *.txt
        echo 2 > 2.txt
        pysleep 1
        type *.txt
        echo 2 > 3.txt
        pysleep 1
        type *.txt
