name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
        where cmake
        call vcvars64.bat
        where cmake
        pyfind C:\Miniconda > conda.txt
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: conda
        path: conda.txt
